webtalk_init -webtalk_dir C:/Users/Mamta Nallaretnam/Desktop/sem2/computer organization/Nanoprocessor1/Nanoprocessor1/Nanoprocessor1.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 11 17:18:04 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fdb62f42-f319-44c2-a374-d9262661f5f9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7c2683d485124736b0fe344126b02973" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "80 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "74" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "48" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "51836_KB" -context "xsim\\usage"
webtalk_transmit -clientid 826781788 -regid "" -xml C:/Users/Mamta Nallaretnam/Desktop/sem2/computer organization/Nanoprocessor1/Nanoprocessor1/Nanoprocessor1.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Mamta Nallaretnam/Desktop/sem2/computer organization/Nanoprocessor1/Nanoprocessor1/Nanoprocessor1.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Mamta Nallaretnam/Desktop/sem2/computer organization/Nanoprocessor1/Nanoprocessor1/Nanoprocessor1.sim/sim_1/behav/xsim/xsim.dir/TB_Nanoprocessor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
